// Extension message types for communication between components
export const EXTENSION_MESSAGES = {
  GET_PAGE_INFO: 'GET_PAGE_INFO',
  TOGGLE_TRANSLATION: 'TOGGLE_TRANSLATION',
  GET_TRANSCRIPT_WITH_AUTH: 'GET_TRANSCRIPT_WITH_AUTH',
  OPEN_TAB: 'OPEN_TAB',
  TOGGLE_TRANSCRIPT_OVERLAY: 'TOGGLE_TRANSCRIPT_OVERLAY',
  UPDATE_LANGUAGE_SETTINGS: 'UPDATE_LANGUAGE_SETTINGS',
} as const;
